matrix:
  include:
  #- os: windows
os: linux
dist: bionic
sudo: required

  # GCC 9
  - name: GCC 9 Linux
    addons: &gcc9
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - pkg-config
        - ninja-build
        - cmake
        - gcc-9
        - g++-9
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libglfw3-dev
        - libwayland-dev
        - libx11-dev
    language: cpp
    compiler: gcc
    env:
    - COMPILER=g++-9
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    - BUILD_SHARED=ON
    - SET_SHIPPING=ON
    before_install:
    - sudo apt-get update -qq
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90

# Clang 8
  - name: Clang 8 Release
    addons: &clang8
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - pkg-config
        - ninja-build
        - cmake
        - g++-8
        - clang-8
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libopenal-dev
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++-8
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Release
    - BUILD_SHARED=ON
    - SET_SHIPPING=ON
    before_install:
    - sudo apt-get update -qq

# Clang 8
  - name: Clang 8 Debug
    addons: &clang8
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - pkg-config
        - ninja-build
        - cmake
        - g++-8
        - clang-8
        - xorg-dev
        - libglu1-mesa-dev
        - libvulkan-dev
        - libopenal-dev
    language: cpp
    compiler: clang
    env:
    - COMPILER=clang++-8
    - GSL_CXX_STANDARD=17
    - BUILD_TYPE=Debug
    - BUILD_SHARED=ON
    - SET_SHIPPING=OFF
    before_install:
    - sudo apt-get update -qq

# Clang 10
- name: Clang 8 Release
  stage: Latest
  addons: &clang10
    apt:
      sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-10
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      packages:
      - pkg-config
      - ninja-build
      - cmake
      - clang-10
      - xorg-dev
      - libglu1-mesa-dev
      - libvulkan-dev
      - libopenal-dev
  language: cpp
  compiler: clang
  env:
  - CXX=clang++-10
  - GSL_CXX_STANDARD=17
  - BUILD_TYPE=Release
  - BUILD_SHARED=ON
  - SET_SHIPPING=ON
  before_install:
  - sudo apt-get update -qq

script:
- git submodule update --init --recursive
- mkdir Build && cd Build
- cmake .. -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDEFINE_SHIPPING=$SET_SHIPPING
- ninja
