language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - llvm-toolchain-trusty-7
    packages:
      - cmake
      - cmake-data
      - g++-7
      - clang-7

git:
  submodules: true


install:
  - if [[ "$CXX" == "g++" ]];     then export CC="gcc-7"      ;fi
  - if [[ "$CXX" == "g++" ]];     then export CXX="g++-7"     ;fi
  
# Universal Setup
before_script:
  - mkdir build
  - cmake . -B build
  - cd build
  - cmake --build . 