# build version format
version: '{build}'

# Free accounts have a max of 1, but ask anyway.
max_jobs: 4

# Any VSVisual studio version we want
image:
- Visual Studio 2019
- Visual Studio 2017
- Visual Studio 2015

configuration:
- Debug
- Release

# Enviornment variable matrix
environment:
  matrix:
  - DDEFINE_SHIPPING: 0
  - DDEFINE_SHIPPING: 1
  - DWITH_LUA_FLAG: 0
  - DWITH_LUA_FLAG: 1

# We only care about x64 for right now
platform:
- x64

# If we had a specific CMake version we wanted 
# this is the place to add it
install:
# Vulkan maybe? 
  - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%"
  - echo Starting build for %APPVEYOR_REPO_NAME% in %APPVEYOR_BUILD_FOLDER%
  - cmake --version
  # Build Vulkan-Headers
  - echo Building Vulkan-Headers for %PLATFORM% %CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/KhronosGroup/Vulkan-Headers.git
  - cd Vulkan-Headers
  - mkdir build
  - cd build
  - cmake -A %PLATFORM% -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config %CONFIGURATION% --target install -- /maxcpucount
  # Build Vulkan-Loader
  - echo Building Vulkan-Loader for %PLATFORM% %CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/KhronosGroup/Vulkan-Loader.git
  - cd Vulkan-Loader
  - mkdir build
  - cd build
  - cmake -A %PLATFORM% -DVULKAN_HEADERS_INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%/Vulkan-Headers/build/install -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config %CONFIGURATION% --target install -- /maxcpucount
# Build Fling
  - cmake --version
  - echo Generating platform=%PLATFORM% configuration=%CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake .. -A %PLATFORM%
  - dir
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

build:
  parallel: true                  # enable MSBuild parallel builds
  project: build/FlingEngine.sln # path to Visual Studio solution or project
  verbosity: normal                # quiet|minimal|normal|detailed